name: Manual Deploy workflow

on:
  workflow_dispatch:

env:
  MINIKUBE_VERSION: v1.20.0
  KUBERNETES_VERSION: v1.20.4

jobs:
  GetInfo:
    name: GetInfo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: apogiatzis/ngrok-tunneling-action@v0.1.4
        with:
          port: 80
          ngrok_authtoken: 1234
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.3.1
        with:
          minikube version: '${{ env.MINIKUBE_VERSION }}'
          kubernetes version: '${{ env.KUBERNETES_VERSION }}'
          start args: '--addons=ingress'
      - name: Minikube Info
        run: |
          ip a
          curl -sk https://ipinfo.io
          minikube ip
          kubectl get nodes
          kustomize version
          sleep 1h
  Client:
    name: Client
    runs-on: ubuntu-latest
    steps:
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
      - name: spwan shell
        run: |
          sleep 1h
